version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:7.17.6
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node
    networks:
      - elk

  kibana:
    image: kibana:7.17.6
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
